#298 added configurable algorithm.
devonfw/devon4j pull request #332
Opened 2021-01-05 06:08 UTC by sujith-mn

2021-01-07 14:31 UTC, hohwille requested changes
For #71 my expecation would be:
* we understand why the default algorithm is flawed and should be discouraged - if noone can clarify this and #71 is invalid, we should simply cose it. Otherwise we need to take action with the next points.
* we understand what algorithm should be our best-practice
* we practically proof the usage with the new algorithm on a running example application
* we change this documentation with concrete steps so all steps and example configs and outputs match to the new algorithm

2021-01-07 14:31 UTC, hohwille commented on documentation/guide-configuration.asciidoc
> +----- ARGUMENTS ```
is this valid AsciiDoc?
Either
```
[source, «type»]
---
```
or
```
\```
```
will start a code block.

If you did rerun jasypt with more recent algorithm you are more than welcome to replace this output examples here. However, I do not understand these changes here...

2021-01-07 14:31 UTC, hohwille commented on documentation/guide-configuration.asciidoc
> +Other configurable properties can be found https://github.com/ulisesbocchio/jasypt-spring-boot#password-based-encryption-configuration[here]
Very nice improvement. Still it is unclear what to do? Which algorithm should we use now?

2021-03-15 08:25 UTC, hohwille approved these changes
@sujith-mn thanks for your updates. I am approving. However, I still have one concern:
If we override the encryption algorithm manually in the jasypt CLI we IMHO also have to configure that in springs `application.properties`, right?
Did you test this and ensure that the password can be decrypted by the devon4j template application following this guide?

Otherwise if the new version of Jasypt has changed the encryption algorithm, do we still need to provide it in the jasypt CLI?

Appart from this last point this is ready for merge.

2021-04-05 07:27 UTC, sujith-mn commented
> @sujith-mn thanks for your updates. I am approving. However, I still have one concern:
> If we override the encryption algorithm manually in the jasypt CLI we IMHO also have to configure that in springs `application.properties`, right?
Yes, if other than default algorithm required, it needs to be configured.
> Did you test this and ensure that the password can be decrypted by the devon4j template application following this guide?
Yes
> Otherwise if the new version of Jasypt has changed the encryption algorithm, do we still need to provide it in the jasypt CLI?
If we do not provide the algorithm in CLI jasypt considers the default algorithm.

> Appart from this last point this is ready for merge.

2021-04-12 08:13 UTC, merged