Feature/284 support for synchronous rest client using http client
devonfw/devon4j pull request #401
Opened 2021-06-16 06:58 UTC by suvmanda

2021-06-16 07:40 UTC, ssarmokadam commented on modules/http-client-rest/src/main/java/com/devonfw/module/httpclient/common/impl/rest/HttpRestClientSyncAutoConfiguration.java
> + * @since 2020.08.001
check from which version feature is available and modify javadoc accordingly

2021-06-16 07:42 UTC, ssarmokadam commented on modules/http-client/src/main/java/com/devonfw/module/httpclient/common/impl/AbstractSyncServiceHttpClient.java
> +    } catch (IOException e) {
Check for exception handling part in asynclient . do not add e.printStackTrace()

2021-06-16 07:43 UTC, ssarmokadam commented on modules/service/src/main/java/com/devonfw/module/service/common/api/client/sync/SyncServiceClientFactory.java
> +  /**
Remove commented code

2021-06-16 07:57 UTC, ssarmokadam requested changes
Check for javadocs on method and modify it for synchronous, check for versions in doc. Also check for error handling part

2021-06-17 10:33 UTC, hohwille requested changes
@suvmanda Thanks for this PR. You have done a great job here. The code looks very well, has nice JavaDoc with `since` tags, code-style is fine. 👍 

However, you extended the API what seems to be a missunderstanding. Can you please check this and if you agree rework your PR?

2021-06-17 10:33 UTC, hohwille commented on modules/service/src/main/java/com/devonfw/module/service/common/api/client/ServiceClientFactory.java
> +  <S> SyncServiceClient<S> createSync(Class<S> serviceInterface);
We already have this API. For historic reasons the methods are called `create`. When async support was added the `createAsync` methods had been added.
I do not see why we have to add `createSync` additionally that would IMHO do the same as the `create` methods. Do I miss something?

2021-06-17 10:33 UTC, hohwille commented on modules/service/src/main/java/com/devonfw/module/service/common/api/client/SyncServiceClient.java
> +public interface SyncServiceClient<S> {
OK. It seems there is a missunderstanding here.
The synchronous access using HTTP should behave exactly like the API we already have existing.
Only the a new implementation option should be added that can be used instead without `cxf-client` dependencies...

IMHO for synchronous invocation this new API seems overcomplicated. I do not have to provide `Consumer` as callback when I can call the code directly.

2021-06-17 10:37 UTC, hohwille commented on modules/service/src/main/java/com/devonfw/module/service/common/api/client/SyncServiceClient.java
> +public interface SyncServiceClient<S> {
See existing documentation:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-service-client.asciidoc#simple-usage

```
 private void callSynchronous(MyArgs myArgs) {
    MyService myService = this.serviceClientFactory.create(MyService.class);
    // call of service over the wire, synchronously blocking until result is received or error occurred
    MyResult myResult = myService.myMethod(myArgs);
    handleResult(myResult);
  }
```

So when replacing dependency `devon4j-starter-cxf-client-rest` with `devon4j-starter-http-client-rest-sync` the same code pattern should work except that under the hood no more CXF but the HttpClient is used.

2021-06-28 15:07 UTC, hohwille requested changes
@suvmanda thanks for your updates. We are getting close. Please have a look at my review comments.
There has been some C&P from the existing code. I can resolve that myself after merging.

2021-06-28 15:07 UTC, hohwille commented on modules/http-client-rest/src/main/java/com/devonfw/module/httpclient/common/impl/rest/SyncServiceClientStubImpl.java
> +
remove outcommented code.

2021-06-28 15:07 UTC, hohwille commented on modules/http-client-rest/src/main/java/com/devonfw/module/httpclient/common/impl/rest/SyncServiceClientStubImpl.java
> +    return null;
Please complete this with proper code.

2021-06-28 15:07 UTC, hohwille commented on modules/http-client-rest/src/main/java/com/devonfw/module/httpclient/common/impl/rest/SyncServiceClientStubImpl.java
> +  private Consumer<Throwable> errorHandler;
should also be removed as this only  makes sense for async usage. There is no API to set this in sync usage and the sync API is designed to throw errors immediately when received.

2021-06-28 15:07 UTC, hohwille commented on modules/http-client/src/main/java/com/devonfw/module/httpclient/common/impl/AbstractSyncServiceHttpClient.java
> +
can you remove all these pointless empty lines between JavaDoc and Signature, please?

2021-07-06 13:54 UTC, hohwille commented
@suvmanda thanks again for your work and this PR. I forked your work and created PR #410 that replaces this PR.
Therefore I am closing this PR.

2021-07-06 13:54 UTC, closed without merging