Add guide for quarkus logic layer
devonfw/devon4j pull request #432
Opened 2021-08-06 11:45 UTC by lilliCao

As discussed with @hohwille, we prefer to use the approach "use-cases without component-facade" for the logic layer implementation. This guide is based on the quarkus code example [here](https://github.com/devonfw-sample/devon4quarkus-reference/pull/7). 

With that said, this is a proposal and I would appreciate any feedback/discussion.

Relate https://github.com/devonfw-sample/devon4quarkus-reference/pull/7 https://github.com/devonfw/devon4j/issues/420
Closes https://github.com/devonfw-forge/devonfw-microservices/issues/38

2021-08-09 06:31 UTC, GuentherJulian commented
Also add your guide to the [devon4j.asciidoc](https://github.com/devonfw/devon4j/blob/master/documentation/devon4j.asciidoc) file, so that the guide is displayed on the website

2021-08-09 06:51 UTC, EduardKrieger approved these changes

2021-08-09 16:51 UTC, hohwille requested changes
@lilliCao thanks for your PR and taking this forward.
IMHO we still struggle to align on the strategy for the documentation.
Sorry, if I did not manage to explain it well enough.
I hope to be able to explain it better in our next standup.
See also [my review here](https://github.com/devonfw/devon4j/pull/435#pullrequestreview-725545768)

It should not depend on spring or quarkus how to implement a use-case. So we should keep this central guide and keep improving it:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-usecase.asciidoc

What can be changed/improved:
* first of all the idea is that you create a class per use-case. For CRUD we wanted to simplify and inveted this `UcFind*` and `UcManage*`. However the focus of the guide should be on some real business logic so something like `UcApproveOrder` or `UcTerminateContract`.
* for simplicity we can state that creating interfaces for the use-cases is optional.
* Also I just re-read the existing usecase guide and was kind of shocked that the "Implementation" part is entirely broken and full of nonsense for 2 years+. We should take out the component-facade stuff that belongs [here](https://github.com/devonfw/devon4j/blob/master/documentation/guide-component-facade.asciidoc).

2021-08-12 12:55 UTC, lilliCao commented
Moved to #439

2021-08-12 12:55 UTC, closed without merging