Add files via upload
devonfw/devon4j pull request #458
Opened 2021-09-21 16:31 UTC by TugbaDalmaz

2021-09-21 16:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw/devon4j?pullRequest=458) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw/devon4j?pullRequest=458) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw/devon4j?pullRequest=458) it.</sub>

2021-09-22 13:27 UTC, EduardKrieger requested changes

2021-09-22 13:27 UTC, EduardKrieger commented on documentation/quarkus/guide-for-testing.asciidoc
> +In Quarkus there are two test dependencies, the JUnit5 and the rest-assured. When using the JUnit5 it must be noted that the Surfire Maven Plugin is set, as the default version does not support the J
Surefire

2021-09-22 13:27 UTC, EduardKrieger commented on documentation/quarkus/guide-for-testing.asciidoc
> +Source: https://quarkus.io/guides/getting-started-testing
I think you can also show or mention the ability to use [continious testing](https://quarkus.io/guides/continuous-testing) with the developement mode in quarkus.

2021-09-22 13:27 UTC, EduardKrieger commented on documentation/quarkus/guide-for-testing.asciidoc
> +Furthermore, Quarkus provides a REST Assured integration without any additional configuration. This uses the updated default port from REST Assured before executing the test. When using REST Assured,
timeouts

2021-09-29 21:58 UTC, GuentherJulian commented
You simply link the Quarkus guide in your guide, which is fine in many cases. But we also need to see if there are any differences with the existing Testing Guide from devon4j. For example, the existing guide for Spring applications says to use AssertJ as the assertion framework. The Quarkus guide depends on REST Assured, if I understand correctly. So the existing guide is not a general guide for Spring and Quarkus, if we say in another guide that the user must use a different framework in Quarkus. Either we need to remove those parts of the general guide and create different guides for Spring and Quarkus. Or we need to check if it is possible to use AssertJ in Quarkus as well. But then we can't just refer to the original Quarkus guide.
In any case we need to link your guide in the general guide so that user can easily jump to your guide when they read something about testing in the general guide.

2021-11-18 07:09 UTC, maybeec commented
closes  devonfw/devon4quarkus#11

2021-11-24 20:53 UTC, EduardKrieger approved these changes

2021-12-11 18:36 UTC, maybeec approved these changes

2021-12-11 18:45 UTC, merged