12-factor app using devon4j
devonfw/devon4j pull request #539
Opened 2022-03-09 11:36 UTC by ssarmokadam

guide on how to create 12-factor app with devon4j

2022-03-16 12:38 UTC, SchettlerKoehler requested changes
First comments. Rest will follow

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +To satisfy this factor consider creating one git/code repository for 1 process.
for each process

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +devon4j application is a maven project so we declare dependencies in pom.xml. For isolation of dependencies we should containerize an application.It will isolate application environment from rest of
Here you are missing a space between the last sentences.

Also, we should add a link on how to put the application in a container. For both quarkus and spring

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +* Anything that will vary between different deploys like in dev, test, staging and prod.
deployments or better deployment environments

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +Never ever hardcode this configurations into code or do not put it in config files. This is because config files are also bundled with source code and this values will change depending on which envir
or -> and

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +This factor has to be considered while designing/implementing your project. Consider reading actual value of property from environment variables.
We should have a guide for that

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +As shown in above image, default value of logging level is INFO but in case I want to change it to debug in test environment to analyze some issue then I do not need to change it into the code or in
image -> code block or code

2022-03-16 12:38 UTC, SchettlerKoehler commented on documentation/12-factor-app-devon4j.asciidoc
> +As shown in above image, default value of logging level is INFO but in case I want to change it to debug in test environment to analyze some issue then I do not need to change it into the code or in
You should point out that every variable should have a reasonable default

2022-03-16 13:01 UTC, maybeec reviewed
Rather than putting a lot of text here and trying to re-explain 12-factors, I would strongly encourage you to introduce 12-factors with only 1-2 sentences referring to 12factor.net for further reading and reading the explanation of the 12 factors.

In addition, you could have a table or even chapters for each factor simply with one sentence referring to some documentation or solution or others. We should not try to re-explain what is understood from the factor, but rather point to the guidelines how devonfw is handling each factor. This could even be multiple different implementations depending on the programming language.

2022-04-02 10:28 UTC, hohwille commented on documentation/12-factor-app-devon4j.asciidoc
> += 12-factor-app with devon4j
The images are nowhere referenced.
Further `12-factor-app-config.JPG` only contains source-code that can be included directly as text into asciidoc.

2022-04-05 05:49 UTC, SchettlerKoehler approved these changes

2022-04-05 05:49 UTC, merged